### ISSUE TITLE
spirv translator assert failure building opencl-neo targets via ocloc

### ISSUE THREAD

**Issue by dvrogozh** [intel/opencl-clang#46] opened 2019-03-08 21:02 UTC
Assuming that IGC and common_clang were built against LLVM-8 per this instruction: https://github.com/dvrogozh/intel-graphics-compiler/blob/rfc_readme/README.md#building

Then building https://github.com/intel/compute-runtime the following build failure could be observed:
```
cd /home/neo/compute-runtime/runtime/scheduler && LD_LIBRARY_PATH=/home/neo/compute-runtime/build/bin /home/neo/compute-runtime/build/bin/ocloc -q -file scheduler.cl -device skl -cl-intel-greater-than-4GB-buffer-required -64 -out_dir /home/neo/compute-runtime/build/bin/scheduler/x64/gen9 -cpp_file -options -I/home/install.llvm8.igc/include/igc\ -I/home/install.llvm8.igc/include/igc/cif\ -I/home/install.llvm8.igc/include/igc/ocl_igc_shared/executable_format\ -I/home/install.llvm8.igc/include/igc/ocl_igc_shared/device_enqueue\ -I\ ../gen9\ -cl-kernel-arg-info\ -cl-std=CL2.0

ocloc: /home/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:685: SPIRV::SPIRVInstruction* SPIRV::LLVMToSPIRV::transUnaryInst(llvm::UnaryInstruction*, SPIRV::SPIRVBasicBlock*): Assertion `Cast->getSrcTy()->getPointerAddressSpace() == SPIRAS_Generic' failed.
```

That's an assert coming from here: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/0650ff887b5ef00066e6a0527bab592dafd59c83/lib/SPIRV/SPIRVWriter.cpp#L685

Also, I have tried to apply patches mentioned by common_clang here: https://github.com/intel/opencl-clang/tree/ocl-open-80/patches. These **patches did not fix the above issue**.

**Comment by dvrogozh** [comment] 2019-03-08 21:32
Assertion is:
`assert(Cast->getSrcTy()->getPointerAddressSpace() == SPIRAS_Generic)`

I just checked that `Cast->getSrcTy()->getPointerAddressSpace()` returns 0. Which is SPIRAS_Private per definition below:

https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/0650ff887b5ef00066e6a0527bab592dafd59c83/lib/SPIRV/SPIRVInternal.h#L181

```
enum SPIRAddressSpace {
  SPIRAS_Private,
  SPIRAS_Global,
  SPIRAS_Constant,
  SPIRAS_Local,
  SPIRAS_Generic,
  SPIRAS_Count,
};
```

**Comment by AlexeySotkin** [comment] 2019-03-11 15:50
The issue is caused by casting `q` from private address space to global. I'm not sure it is legal. Need to investigate it further.

```
__global IGIL_CommandHeader* TEMP_IGIL_GetNthCommandHeader( queue_t q, uint initialOffset, uint number )
{

    __global uchar *pQueueRaw = __builtin_astype( q, __global uchar* );

    __global IGIL_CommandHeader* pCommand = ( __global IGIL_CommandHeader* )( pQueueRaw + initialOffset );

    uint Offset = initialOffset;
    //Traverse queue_t unless nth command packet is found
    while( number > 0 )
    {
        Offset  += pCommand->m_commandSize;
        pCommand = TEMP_IGIL_GetCommandHeader( q, Offset );
        number--;
    }

    return pCommand;
}
```

**Comment by dvrogozh** [comment] 2019-03-11 20:09
Just posting a link to the place in sources pointed by @AlexeySotkin:
https://github.com/intel/compute-runtime/blob/cb39644c694455ff4d78571aeb15f5ede6c17e0f/runtime/scheduler/scheduler.cl#L167

**Comment by AlexeySotkin** [comment] 2019-03-13 12:44
I think the easiest way to fix the issue is to modify scheduler.cl

The kernel gets `pQueue` as argument of type `__global IGIL_CommandQueue*`
`__kernel __attribute__((intel_reqd_sub_group_size(PARALLEL_SCHEDULER_COMPILATION_SIZE_20)))
void SchedulerParallel20(`
    **__global IGIL_CommandQueue\* pQueue,**
   ` __global uint* commandsStack,`

Then it passes `pQueue` to the following function, but for some reason casted to queue_t
`TEMP_IGIL_GetNthCommandHeaderOffset( `**__builtin_astype( pQueue, queue_t )**`, InitialOffset, CurrentPacket );`

But what we do with it in this function is casting to `__global uchar*`
`__global IGIL_CommandHeader* TEMP_IGIL_GetNthCommandHeader( `**queue_t q**`, uint initialOffset, uint number )
{
__global uchar *pQueueRaw = `**__builtin_astype( q, __global uchar* )**`;
`

I believe if we change `TEMP_IGIL_GetNthCommandHeaderOffset` to take `__global IGIL_CommandQueue*` as argument and cast it directly to `__global uchar*` skipping the `queue_t` representation it should be possible to convert it to SPIR-V. 
There are a few other the same cases which should be modified in the same way though.

**Comment by dvrogozh** [comment] 2019-03-13 22:09
@AlexeySotkin: I made a change you've suggested, I pushed it here https://github.com/intel/compute-runtime/pull/143. Unfortunately it seems that some earlier versions of clang don't like the change, but I hope it should be ok for LLVM-8.

I have also stepped into another issue on IGC side building the same command line. https://github.com/intel/intel-graphics-compiler/issues/77. And here is a fix: https://github.com/intel/intel-graphics-compiler/issues/78

**Comment by AlexeySotkin** [comment] 2019-03-14 06:23
@dvrogozh Can we close this issue ?

**Comment by dvrogozh** [comment] 2019-03-14 20:13
Fix in neo did land yet. Can we wait few days till it will be merged? or we will need to submit bug directly against neo.

**Closed** 2019-03-18 15:31 UTC
